[package]
name = "osint-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Cryptography and security for OSINT platform"

[dependencies]
osint-core = { path = "../osint-core" }