[package]
name = "osint-web"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Web server and API for OSINT platform"

[dependencies]
osint-core = { path = "../osint-core" }